/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registracija novog studenta */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Nalog kreiran. Verifikacioni email poslat. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description Email vec postoji */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prijava */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Obnova access tokena */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Odjava (invalidira refresh token) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description Odjavljen */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Potvrda email adrese */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                    };
                };
            };
            responses: {
                /** @description Email potvrdjen */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Zahtev za reset lozinke */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description Uvek 204, cak i ako email ne postoji (sprecava enumeraciju naloga). */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Postavljanje nove lozinke */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                        /** Format: password */
                        newPassword: string;
                    };
                };
            };
            responses: {
                /** @description Lozinka promenjena */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Podaci o prijavljenom korisniku */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista objavljenih proizvoda */
        get: {
            parameters: {
                query?: {
                    type?: components["schemas"]["ProductType"];
                    grade?: components["schemas"]["Grade"];
                    area?: components["schemas"]["SubjectArea"];
                    examPrep?: components["schemas"]["ExamPrep"];
                    /** @description Pretraga po naslovu i opisu */
                    q?: string;
                    sort?: "popular" | "newest" | "priceAsc" | "priceDesc";
                    page?: components["parameters"]["Page"];
                    size?: components["parameters"]["Size"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalj proizvoda
         * @description Za COURSE vraca i listu lekcija (naslovi + trajanje). Sadrzaj lekcije
         *     (playback URL) se NIKAD ne vraca ovde — samo preko /me/library.
         *     Ako je korisnik prijavljen i vec poseduje proizvod, `owned` je true.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: components["parameters"]["Slug"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductDetail"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dostupni filteri sa brojem proizvoda
         * @description Frontend iz ovoga gradi filter panel — ne hardkoduje razrede i oblasti.
         *     Vraca samo vrednosti za koje postoji bar jedan objavljen proizvod.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CatalogFilters"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/instructor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Podaci o predavacu (za "O meni" sekciju) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Instructor"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/testimonials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Utisci studenata za landing stranicu */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Testimonial"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trenutna korpa sa obracunom */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cart"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        /** Praznjenje korpe */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Korpa ispraznjena */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dodavanje proizvoda u korpu
         * @description Kolicina je uvek 1 — digitalni proizvod se ne kupuje dva puta.
         *     Ponovno dodavanje istog proizvoda je idempotentno (204/200, ne duplira).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        productId: string;
                    };
                };
            };
            responses: {
                /** @description Korpa nakon dodavanja */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cart"];
                    };
                };
                /** @description Korisnik vec poseduje ovaj proizvod (aktivan entitlement) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Uklanjanje iz korpe */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    productId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Korpa nakon uklanjanja */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cart"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/coupon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Primena kupona */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        code: string;
                    };
                };
            };
            responses: {
                /** @description Korpa sa primenjenim popustom */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cart"];
                    };
                };
                /** @description Kupon nevazeci, istekao ili iskoriscen */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        /** Uklanjanje kupona */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Korpa bez popusta */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cart"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Istorija porudzbina */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    size?: components["parameters"]["Size"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderPage"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Kreiranje porudzbine iz korpe
         * @description Zamrzava cene iz korpe u OrderItem snapshot-e i vraca porudzbinu u
         *     statusu PENDING. Korpa se NE prazni dok placanje ne uspe.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description UUID koji generise klijent; sprecava duple porudzbine/naplate. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Porudzbina kreirana */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Order"];
                    };
                };
                /** @description Korpa prazna ili cena proizvoda promenjena u medjuvremenu */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalj porudzbine */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Order"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}/invoice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preuzimanje racuna (PDF) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PDF racun */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": string;
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/checkout-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciranje placanja karticom
         * @description Vraca URL provajdera na koji frontend radi redirect. Entitlement-i se
         *     NE izdaju ovde — samo preko webhook-a.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description UUID koji generise klijent; sprecava duple porudzbine/naplate. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        orderId: string;
                        /** Format: uri */
                        returnUrl?: string;
                        /** Format: uri */
                        cancelUrl?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            paymentId: string;
                            /** Format: uri */
                            redirectUrl: string;
                            /** Format: date-time */
                            expiresAt?: string;
                        };
                    };
                };
                /** @description Porudzbina vec placena ili otkazana */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Webhook payment provajdera
         * @description Nije za frontend. Verifikuje potpis, prelazi porudzbinu u PAID i izdaje
         *     entitlement-e. Mora biti idempotentan — provajderi ponavljaju isporuku.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description Primljeno */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Neispravan potpis */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kupljeni sadrzaj korisnika */
        get: {
            parameters: {
                query?: {
                    includeExpired?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LibraryEntry"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/library/videos/{videoId}/playback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Potpisan URL za reprodukciju
         * @description Vraca kratkorocan potpisan URL. 403 ako korisnik nema aktivan
         *     entitlement za taj video. Frontend ovaj URL ne kesira.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    videoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlaybackToken"];
                    };
                };
                /** @description Nema pristup ili je pristup istekao */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Napredak po lekcijama */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Progress"][];
                    };
                };
            };
        };
        /**
         * Azuriranje pozicije gledanja
         * @description Frontend salje na svakih ~15 sekundi i na pauzi/napustanju.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        videoId: string;
                        positionSec: number;
                        completed?: boolean;
                    };
                };
            };
            responses: {
                /** @description Sacuvano */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Izmena profila */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        fullName?: string;
                        script?: components["schemas"]["Script"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Svi proizvodi ukljucujuci neobjavljene */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    size?: components["parameters"]["Size"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductPage"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** Kreiranje proizvoda */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductWriteRequest"];
                };
            };
            responses: {
                /** @description Kreirano */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Izmena proizvoda */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    productId: components["parameters"]["ProductId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductWriteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductDetail"];
                    };
                };
            };
        };
        post?: never;
        /** Brisanje (soft delete — postavlja published=false) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    productId: components["parameters"]["ProductId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Obrisano */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/videos/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dobijanje URL-a za direktan upload videa kod provajdera */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        fileName: string;
                        title: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uri */
                            uploadUrl?: string;
                            providerVideoId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/coupons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista kupona */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Coupon"][];
                    };
                };
            };
        };
        put?: never;
        /** Kreiranje kupona */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Coupon"];
                };
            };
            responses: {
                /** @description Kreirano */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Coupon"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sve porudzbine */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["OrderStatus"];
                    page?: components["parameters"]["Page"];
                    size?: components["parameters"]["Size"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/entitlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rucno dodeljivanje pristupa (poklon, podrska, produzenje) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        userId: string;
                        /** Format: uuid */
                        productId: string;
                        /** Format: date-time */
                        expiresAt?: string | null;
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description Dodeljeno */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LibraryEntry"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ProductType: "VIDEO" | "COURSE" | "BUNDLE";
        /**
         * @description Razred osnovne ili srednje skole.
         * @enum {string}
         */
        Grade: "OS_5" | "OS_6" | "OS_7" | "OS_8" | "SS_1" | "SS_2" | "SS_3" | "SS_4";
        /**
         * @description Oblast gradiva srpskog jezika i knjizevnosti.
         * @enum {string}
         */
        SubjectArea: "GRAMATIKA" | "PRAVOPIS" | "KNJIZEVNOST" | "LEKTIRA" | "PISMENO_IZRAZAVANJE" | "GOVORNE_VEZBE";
        /**
         * @description Priprema za ispit; null kod redovnog gradiva.
         * @enum {string}
         */
        ExamPrep: "MALA_MATURA" | "UPIS_SREDNJA" | "MATURA" | "PRIJEMNI_FAKULTET";
        /**
         * @description DAYS       — pristup traje N dana od kupovine
         *     UNTIL_DATE — pristup traje do fiksnog datuma (kraj skolske godine)
         *     LIFETIME   — bez roka
         * @enum {string}
         */
        AccessMode: "DAYS" | "UNTIL_DATE" | "LIFETIME";
        /** @enum {string} */
        OrderStatus: "PENDING" | "PAID" | "FAILED" | "CANCELLED" | "REFUNDED";
        /** @enum {string} */
        PaymentStatus: "INITIATED" | "AUTHORIZED" | "CAPTURED" | "FAILED" | "REFUNDED";
        /** @enum {string} */
        UserRole: "STUDENT" | "ADMIN";
        /** @enum {string} */
        EntitlementSource: "ORDER" | "GIFT" | "PROMO" | "MANUAL";
        /** @enum {string} */
        DiscountType: "PERCENT" | "FIXED";
        /** @description RFC 7807 Problem Details */
        Problem: {
            /**
             * Format: uri
             * @example https://srpski-online.rs/errors/coupon-invalid
             */
            type: string;
            /** @example Kupon nije validan */
            title: string;
            /** @example 422 */
            status: number;
            /** @example Kupon LETO2026 je istekao 31.08.2026. */
            detail?: string;
            instance?: string;
            /**
             * @description Stabilan masinski kod za frontend i18n mapiranje.
             * @example COUPON_EXPIRED
             */
            code?: string;
            /** @description Greske po poljima kod validacije. */
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            fullName: string;
            script?: components["schemas"]["Script"];
            acceptTerms?: boolean;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        AuthResponse: {
            accessToken: string;
            refreshToken: string;
            /**
             * @description Trajanje access tokena u sekundama.
             * @example 900
             */
            expiresIn: number;
            user: components["schemas"]["User"];
        };
        /**
         * @description Pismo interfejsa. Sadrzaj lekcija je uvek na srpskom.
         * @default lat
         * @enum {string}
         */
        Script: "lat" | "cyr";
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            fullName: string;
            role: components["schemas"]["UserRole"];
            emailVerified: boolean;
            script?: components["schemas"]["Script"];
            /** Format: date-time */
            createdAt?: string;
        };
        Money: {
            /**
             * Format: int64
             * @description Iznos u najmanjoj jedinici valute (pare).
             * @example 150000
             */
            amountMinor: number;
            /** @example RSD */
            currency: string;
        };
        ProductSummary: {
            /** Format: uuid */
            id: string;
            /** @example pocetni-kurs-a1 */
            slug: string;
            type: components["schemas"]["ProductType"];
            title: string;
            shortDescription?: string;
            /** @description Jedan proizvod moze pokrivati vise razreda. */
            grades?: components["schemas"]["Grade"][];
            areas?: components["schemas"]["SubjectArea"][];
            examPrep?: components["schemas"]["ExamPrep"] | null;
            /**
             * @description Skolska godina za koju vazi sadrzaj.
             * @example 2026/2027
             */
            schoolYear?: string | null;
            price: components["schemas"]["Money"];
            /** @description Precrtana stara cena, ako postoji akcija. */
            compareAtPrice?: components["schemas"]["Money"] | null;
            accessMode?: components["schemas"]["AccessMode"];
            /**
             * @description Popunjeno samo kada je accessMode = DAYS.
             * @example 90
             */
            accessDurationDays?: number | null;
            /**
             * Format: date
             * @description Popunjeno samo kada je accessMode = UNTIL_DATE.
             * @example 2027-08-31
             */
            accessUntil?: string | null;
            /** Format: uri */
            coverUrl: string;
            lessonCount?: number;
            totalDurationSec?: number;
            /** @description True samo ako je zahtev autentifikovan i korisnik ima pristup. */
            owned?: boolean;
            published?: boolean;
        };
        ProductDetail: components["schemas"]["ProductSummary"] & {
            /** @description Markdown dozvoljen. */
            description?: string;
            whatYouWillLearn?: string[];
            requirements?: string[];
            /** @description Popunjeno za COURSE. */
            lessons?: components["schemas"]["Lesson"][];
            /** @description Popunjeno za BUNDLE. */
            includedProducts?: components["schemas"]["ProductSummary"][];
            instructor?: components["schemas"]["Instructor"];
        };
        Lesson: {
            /** Format: uuid */
            videoId: string;
            title: string;
            description?: string;
            /** @example 725 */
            durationSec: number;
            orderIndex: number;
            /** @description Ako je true, playback je dostupan i bez kupovine. */
            isFreePreview: boolean;
            hasAttachments?: boolean;
        };
        ProductWriteRequest: {
            type: components["schemas"]["ProductType"];
            title: string;
            slug: string;
            shortDescription?: string;
            description?: string;
            grades?: components["schemas"]["Grade"][];
            areas?: components["schemas"]["SubjectArea"][];
            examPrep?: components["schemas"]["ExamPrep"] | null;
            schoolYear?: string | null;
            /** Format: int64 */
            priceMinor: number;
            /** Format: int64 */
            compareAtPriceMinor?: number | null;
            currency: string;
            accessMode?: components["schemas"]["AccessMode"];
            accessDurationDays?: number | null;
            /** Format: date */
            accessUntil?: string | null;
            /** Format: uri */
            coverUrl?: string;
            published?: boolean;
            /** @description Samo za BUNDLE. */
            includedProductIds?: string[];
            whatYouWillLearn?: string[];
        };
        ProductPage: {
            content: components["schemas"]["ProductSummary"][];
            page: number;
            size: number;
            /** Format: int64 */
            totalElements: number;
            totalPages: number;
        };
        FilterOption: {
            /** @example OS_7 */
            value: string;
            /** @example 7. razred */
            label: string;
            /** @example 12 */
            count: number;
        };
        CatalogFilters: {
            grades?: components["schemas"]["FilterOption"][];
            areas?: components["schemas"]["FilterOption"][];
            examPrep?: components["schemas"]["FilterOption"][];
        };
        Instructor: {
            /** @example Prof. Ime Prezime */
            fullName?: string;
            /** @example Profesor srpskog jezika i knjizevnosti */
            title?: string;
            bio?: string;
            /** Format: uri */
            photoUrl?: string;
            yearsExperience?: number;
            studentsCount?: number;
        };
        Testimonial: {
            /** Format: uuid */
            id?: string;
            studentName?: string;
            grade?: components["schemas"]["Grade"] | null;
            /**
             * @description Konkretan ishod, npr. bodovi na maloj maturi.
             * @example 19/20 na maloj maturi
             */
            result?: string | null;
            rating?: number;
            text?: string;
            /** Format: uri */
            avatarUrl?: string | null;
        };
        Cart: {
            items: components["schemas"]["CartItem"][];
            couponCode?: string | null;
            subtotal: components["schemas"]["Money"];
            discount: components["schemas"]["Money"];
            total: components["schemas"]["Money"];
            /** Format: date-time */
            updatedAt?: string;
        };
        CartItem: {
            /** Format: uuid */
            productId: string;
            slug?: string;
            title: string;
            type?: components["schemas"]["ProductType"];
            /** Format: uri */
            coverUrl?: string;
            price: components["schemas"]["Money"];
            accessMode?: components["schemas"]["AccessMode"];
            accessDurationDays?: number | null;
            /** Format: date */
            accessUntil?: string | null;
            /** Format: date-time */
            addedAt?: string;
        };
        Order: {
            /** Format: uuid */
            id: string;
            /**
             * @description Citljiv broj za korisnika i racun.
             * @example SO-2026-000148
             */
            orderNumber: string;
            status: components["schemas"]["OrderStatus"];
            items: components["schemas"]["OrderItem"][];
            couponCode?: string | null;
            subtotal: components["schemas"]["Money"];
            discount: components["schemas"]["Money"];
            total: components["schemas"]["Money"];
            payment?: components["schemas"]["PaymentSummary"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            paidAt?: string | null;
        };
        OrderItem: {
            /** Format: uuid */
            productId: string;
            /** @description Naslov u trenutku kupovine — ne menja se retroaktivno. */
            titleSnapshot: string;
            priceSnapshot: components["schemas"]["Money"];
            accessModeSnapshot?: components["schemas"]["AccessMode"];
            accessDurationDaysSnapshot?: number | null;
            /** Format: date */
            accessUntilSnapshot?: string | null;
            type?: components["schemas"]["ProductType"];
        };
        OrderPage: {
            content?: components["schemas"]["Order"][];
            page?: number;
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            totalPages?: number;
        };
        PaymentSummary: {
            /** Format: uuid */
            id?: string;
            /** @example monri */
            provider?: string;
            status?: components["schemas"]["PaymentStatus"];
            /** @example visa */
            cardBrand?: string;
            /** @example 4242 */
            last4?: string;
            /** Format: date-time */
            processedAt?: string;
        } | null;
        Coupon: {
            /** @example LETO2026 */
            code: string;
            discountType: components["schemas"]["DiscountType"];
            /**
             * @description Za PERCENT 1-100, za FIXED iznos u parama.
             * @example 20
             */
            value: number;
            /** Format: date-time */
            validFrom?: string;
            /** Format: date-time */
            validTo?: string;
            maxUses?: number | null;
            readonly usedCount?: number;
            /** Format: int64 */
            minSubtotalMinor?: number | null;
            /** @description null = vazi za sve proizvode. */
            appliesToProductIds?: string[] | null;
            active?: boolean;
        };
        LibraryEntry: {
            /** Format: uuid */
            entitlementId: string;
            product: components["schemas"]["ProductSummary"];
            source?: components["schemas"]["EntitlementSource"];
            /** Format: date-time */
            grantedAt: string;
            /**
             * Format: date-time
             * @description null = dozivotan pristup.
             */
            expiresAt?: string | null;
            accessMode?: components["schemas"]["AccessMode"];
            /** @description Izracunato na serveru radi prikaza "Istice za N dana". */
            daysRemaining?: number | null;
            active: boolean;
            progressPercent?: number;
        };
        PlaybackToken: {
            /** Format: uuid */
            videoId: string;
            /**
             * Format: uri
             * @description Potpisan HLS manifest URL. Kratkorocan, ne kesirati.
             */
            playbackUrl: string;
            /** Format: uri */
            thumbnailUrl?: string;
            /** @example 3600 */
            expiresIn: number;
            durationSec?: number;
            resumeAtSec?: number;
            subtitles?: {
                /** @example en */
                lang?: string;
                /** @example English */
                label?: string;
                /** Format: uri */
                url?: string;
            }[];
            attachments?: {
                /** @example Vezbanja - lekcija 3.pdf */
                name?: string;
                /** Format: uri */
                url?: string;
                /** Format: int64 */
                sizeBytes?: number;
            }[];
        };
        Progress: {
            /** Format: uuid */
            videoId?: string;
            /** Format: uuid */
            productId?: string;
            lastPositionSec?: number;
            completed?: boolean;
            /** Format: date-time */
            updatedAt?: string;
        };
    };
    responses: {
        /** @description Neispravan zahtev */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Nije prijavljen ili je token istekao */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Nema ovlascenje */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Nije pronadjeno */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        Page: number;
        Size: number;
        Slug: string;
        ProductId: string;
        /** @description UUID koji generise klijent; sprecava duple porudzbine/naplate. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
